from openea.approaches.aligne import AlignE
from openea.approaches.bootea import BootEA
from openea.approaches.jape import JAPE
from openea.approaches.attr2vec import Attr2Vec
from openea.approaches.mtranse import MTransE
from openea.approaches.gcn_align import GCN_Align
from openea.approaches.iptranse import IPTransE
from openea.approaches.attre import AttrE
from openea.approaches.imuse import IMUSE
from openea.approaches.sea import SEA
from openea.approaches.rsn4ea import RSN4EA
from openea.approaches.multi_ke import MultiKE
from openea.approaches.gmnn import GMNN
from openea.approaches.kdcoe import KDCoE
from openea.approaches.rdgcn import RDGCN
from openea.approaches.nmn import NMN
from openea.approaches.paris import PARIS
from openea.approaches.rlea import RLEA
from openea.approaches.bootea_rotate import BootEA_RotatE
from openea.approaches.bootea_transh import BootEA_TransH
from openea.approaches.alinet import AliNet
from openea.approaches.rlco import RLCO
from openea.approaches.cycle import Cycle
from openea.approaches.emb_paris import EMB_PARIS
from openea.approaches.hiea import HIEA
from openea.approaches.transformer4ea_bce import Transformer4EA
from openea.approaches.rrea import RREA
from openea.approaches.ke_gcn import KE_GCN
